app = "yassin-portfolio"
kill_signal = "SIGINT"
kill_timeout = 5

[build]

[env]
  DATA_DIR = "/data"
  UPLOAD_DIR = "/data/uploads"

[[mounts]]
  source = "portfolio_data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "5s"
